language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack: 
  email:
  - ademo@126.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: OVquusTXLCvolaPwDGtUZFIrAjSkmDv7TKZSBgh0azZTEbeqWHnqozgHO919a5fW/0OmmFS6M2Onu/4YiD/FIAZkgbsIVdtl/hACqSuzP4KovJFx8oQoJwyJGkVm28BJFc99fxVJBorytWnXwMAE8ds1VdbXwbARP0oOkP2wD3NNZ3nco749hrGuoXifnP2qJdimmWx+Oz1eFBfzHtSWGDs+qOQsfUeo7/HcCMOwI5ytJQNzdyWIvO7JCbAiq2UFwn4RO+SRPOE0KWiYOLW1TJBVNJqy6pEUZ1XzlKpmggiYw+VKZQ5BUBZDlaH0Ru1UvY1bjQxAdG3i8hFwlPCf9uc3I6O+F6Yf0PdTZBxu6hzmxmqOXKG0lLRjKbnU9seF39LpkX9MgYUwrBdE9xQgM1t+Q05SHRA0Osfos3hJZ+qFbAzObz4lLCJ3ISLJYOZfVxT+DYCFOKJnVoIkxIr95V+upaHe2b7tDebMzvJkeq8192/YByp2ysjyLvMlUhU8b3DxoJ82TYGuYxd/PLlyp9ameEO8vY05oSkJGAaBGZ+prRt0/IXQTxbdaDiMC5wJn7Ua5sm526O4NAsC82sW0Ur7zhkPc3133vexbJHJ8tUr0SvYbuafS1+Mcf5juPtWurWZMEQcZ/aWvK2CyYilkuKUIrvxkJuqZVb9Mbk9V3k=
  - secure: CSk0S6r9Q9n0RTsxZ3ViBY1P/Bzd5iTllU8P6so9glVKAq4iIUl8ZXR+3oDtZCSe7raLrYAEcqg1XUJMzYRfAnHj0O3e8wGSaxzK2kG41XkcAlN4/OPnqUB3YYEIB7ejkvPGNwAT99Y6Sp4JHEyGBSbF1BxZIv5GAPcBf6sD/VxSKf3sPM41Pj4tPsBqM3PwSFC7Pb9Db12Uq4J3tXBhfRoA8g10tGzYpycFfUQJDtIpj9cnfyymKCiwQ+IczOLYZSrFaKfVAbD6FH9kdvb6OPItm1V2oG0+2m7brenFbozbhSdCq6izlOB4cpiDqe7RUv4jyNDspmuQMroXnYLXgC6UzRBwMvwkJ4Pi2DgpE8sSedlFP2LJhQde4jQNSMcLVVs1Wr7Wh19z2/0/o89C0SL06afBFskM5/CltVNrItEc1dZxHjrHlS/rovzEz8vPP3oA1zWavegSWWZ+9J95FkeLApUt8T1EdRTzR8PVFicKzXl7dBT0L7iMXQQP2wPdeFd8CptxFPvCF/hodCwGDXgdbTFmQyltYDPuHvX5RQbtO1SA2Tzs7u4uq009U1ujTvCs1v9VWJINPGrg675WB10jLSdoZ/QBg0CLoxA3H0NwU7xGzEZ5ufG9lD9Uf+yWrGNI9dbQV3/acsP3T7pzZcBQlp7zMZQx/veoLFsJwUk=
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker push ademo/tmx-licensing-service:chapter4
- docker push ademo/tmx-organization-service:chapter4
- docker push ademo/tmx-confsvr:chapter4
- docker push ademo/tmx-eurekasvr:chapter4
